docroot/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Deleted/unpublished routes.
  get "highlights/:id/publish", to: "highlights#publish"
  get "highlights/:id/unpublish", to: "highlights#unpublish"
  get "highlights/deleted", to: "highlights#deleted"
  get "highlights/untagged", to: "highlights#untagged"

  # Favorites routes.
  get "highlights/:id/favorite", to: "highlights#favorite"
  get "highlights/:id/unfavorite", to: "highlights#unfavorite"
  get "favorites", to: "highlights#favorites"

  # Search.
  get "highlights/search", to: "highlights#search"

  # Tags.
  get "tags/merge", to: "tags#merge"
  post "tags/merge", to: "tags#merge_post"

  # Autocomplete.
  resources :tags do
    get :autocomplete_tags_title, on: :collection
  end
  resources :sources do
    get :autocomplete_authors_name, on: :collection
  end

  # Resources.
  resources :authors
  resources :highlights
  resources :sources
  resources :tags

  # User settings.
  get "settings", to: "users#settings"
  patch "user/:id", to: "users#update", as: :user

  # Import.
  get "import", to: "import#form"
  post "import", to: "import#import"
  post "upload", to: "import#upload"

  # Root page.
  root "highlights#index"
end

docroot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Commonplace Book: <%= yield(:title) %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Commonplace Book</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to 'Highlights', highlights_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Favorites', '/favorites', class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Tags', tags_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Sources', sources_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Authors', authors_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Import', '/import', class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Settings', '/settings', class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'React', '/react', class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Logout', '/users/sign_out', method: :delete, class: 'nav-link' %></li>
            <li class="nav-item search">
              <%= form_with url: highlights_search_path, method: 'get', local: true, class: 'search-form' do |f| %>
              <%= f.text_field :search, size: 10, value: params["search"] %>
              <%= f.select :model, options_for_select(["Highlights", "Sources", "Authors", "Tags"], params["model"]), include_blank: "All" %>
              <%= f.submit "Search" %>
            <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if flash[:alert] %>
        <div class="flash alert badge badge-warning"><%= flash[:alert] %></div>
      <% end %>
      <% if flash[:notice] %>
        <div class="flash notice badge badge-info"><%= flash[:notice] %></div>
      <% end %>

      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>