docroot/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Deleted/unpublished routes.
  get "highlights/:id/publish", to: "highlights#publish"
  get "highlights/:id/unpublish", to: "highlights#unpublish"
  get "highlights/deleted", to: "highlights#deleted"
  get "highlights/untagged", to: "highlights#untagged"

  # Favorites routes.
  get "highlights/:id/favorite", to: "highlights#favorite"
  get "highlights/:id/unfavorite", to: "highlights#unfavorite"
  get "favorites", to: "highlights#favorites"

  # Search.
  get "highlights/search", to: "highlights#search"

  # Tags.
  get "tags/merge", to: "tags#merge"
  post "tags/merge", to: "tags#merge_post"

  # Autocomplete.
  resources :tags do
    get :autocomplete_tags_title, on: :collection
  end
  resources :sources do
    get :autocomplete_authors_name, on: :collection
  end

  # Resources.
  resources :authors
  resources :highlights
  resources :sources
  resources :tags

  # User settings.
  get "settings", to: "users#settings"
  patch "user/:id", to: "users#update", as: :user

  # Import.
  get "import", to: "import#form"
  post "import", to: "import#import"
  post "upload", to: "import#upload"

  # Root page.
  root "highlights#index"
end

docroot/app/models/source.rb
# frozen_string_literal: true

class Source < ApplicationRecord
  include Authors
  include ByUser
  include Tags

  belongs_to :user
  has_many :highlights, dependent: :delete_all
  has_many :sources_authors, dependent: :delete_all
  has_many :authors, through: :sources_authors
  has_many :source_taggings, dependent: :delete_all
  has_many :tags, through: :source_taggings
  validates :user_id, numericality: { only_integer: true }
  validates_with SourceAuthorValidator
  validates_presence_of :title, message: "is required"
  validates_presence_of :authors, message: "is required"
  validates_presence_of :source_type, message: "is required"
  mount_uploader :file, FileUploader
end

docroot/app/controllers/api/v1/sources_controller.rb
# frozen_string_literal: true

class Api::V1::SourcesController < ApplicationController
  require "will_paginate/array"

  def index
    @sources = current_user.sources
    render json: @sources
  end

  def create
    source = Source.create(source_params)
    render json: source
  end

  def destroy
    Source.destroy(params[:id])
  end

  def update
    source = Source.find(params[:id])
    source.update_attributes(source_params)
    render json: source
  end

  private
    # Define which source fields are required and permitted.
    def source_params
      params.require(:source).permit(:title, :all_authors, :all_tags, :source_type, :notes, :user_id)
    end
end

docroot/app/controllers/sources_controller.rb
# frozen_string_literal: true

# Sources controller.
class SourcesController < ApplicationController
  require "will_paginate/array"
  include SourcesControllerConcern

  # Create a new source.
  def new
    @source = Source.new
    if params[:author]
      @author = params[:author]
    end
  end

  # List sources by user.
  def index
    @sources = current_user.sources
    @source_types = @sources.select(:source_type).distinct.sort_by(&:source_type)
    if params[:source_type].present?
      @sources = @sources.where(source_type: params[:source_type])
    end

    # Sort.
    if params[:sort] == "title"
      @sources = @sources.sort_by(&:title)
    else
      @sources = @sources.sort_by(&:created_at).reverse
    end
  end

  # Show a source.
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @source = current_user.sources.find(params[:id])
    @tags = current_user.tags.by_source(params[:id]).order(:title)
    @highlights = @source.highlights.where(published: true)
    @highlights_count = @highlights.count
    @favorites_count = @highlights.where(favorite: true).count
    if params[:favorite].present?
      @highlights = @highlights.where(favorite: true)
    end
    if params[:tag].present?
      @highlights = @highlights.tagged_with(params[:tag])
    end
    @highlights = @highlights.sort_by(&:location)
  end

  # Edit an existing source.
  def edit
    @source = current_user.sources.find(params[:id])
    @author = authors_comma_separated(@source)
  end

  # Update an existing source.
  def update
    @source = current_user.sources.find(params[:id])
    @author = authors_comma_separated(@source)

    # Change all_authors to be an array containing the comma separated list of
    # authors and the current user ID. We need the user ID in order to save the
    # author to the correct user when creating a new author, since the author
    # doesn't already have the user_id saved.
    params = source_params.merge('all_authors': [
                                   source_params["all_authors"],
                                   source_params["user_id"],
                                 ])
    params = params.merge('all_tags': [
                            source_params["all_tags"],
                            source_params["user_id"],
                          ])

    if @source.update(params)
      redirect_to @source
    else
      render "edit"
    end
  end

  # Create a new source.
  def create
    # Change all_authors to be an array containing the comma separated list of
    # authors and the current user ID. We need the user ID in order to save the
    # author to the correct user when creating a new author, since the author
    # doesn't already have the user_id saved.
    params = source_params.merge('all_authors': [
                                   source_params["all_authors"],
                                   source_params["user_id"],
                                 ])
    params = params.merge('all_tags': [
                            source_params["all_tags"],
                            source_params["user_id"],
                          ])

    @source = Source.new(params)

    if @source.save
      redirect_to @source
    else
      render "new"
    end
  end

  # Delete a source.
  def destroy
    @source = current_user.sources.find(params[:id])
    @source.destroy

    redirect_to sources_path
  end

  # Autocomplete authors for the user.
  def autocomplete_authors_name
    term = params[:term]

    # Get terms already entered to ensure we don't suggest terms already taken.
    existing_authors = params[:all_authors].split(",")
    existing_authors.pop
    existing_authors = existing_authors.map do |existing_author|
      existing_author.strip
    end

    if existing_authors.empty?
      authors = current_user.authors.where("name LIKE ?", "#{term}%").order(:name).all | current_user.authors.where("name LIKE ?", "%#{term}%").order(:name).all
    else
      authors = current_user.authors.where("name LIKE ?", "#{term}%").where("name NOT IN (?)", Array.wrap(existing_authors)).order(:name).all | current_user.authors.where("name LIKE ?", "%#{term}%").where("name NOT IN (?)", Array.wrap(existing_authors)).order(:name).all
    end

    render json: authors.map { |author| { id: author.id, label: author.name, value: author.name } }
  end

  private
    # Define which source fields are required and permitted.
    def source_params
      params.require(:source).permit(:title, :all_authors, :all_tags, :source_type, :notes, :file, :file_cache, :remove_file, :user_id)
    end
end

docroot/app/helpers/sources_helper.rb
# frozen_string_literal: true

module SourcesHelper
  # Given a source, print out comma separated list of authors (links).
  def print_authors(source)
    source.authors.map { |author| link_to(author.name, author_path(author)) }.join(", ").html_safe
  end
end

docroot/app/views/sources/_form.html.erb
<%= form_with model: @source, multipart: true, local: true do |form| %>

  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@source.errors.count, "error") %> prohibited
        this source from being saved:
      </h2>
      <ul>
        <% @source.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag(:title) %><br>
    <%= form.text_field :title, class: 'form-control', id: 'title' %>
  </div>

  <div>
    <%= label_tag(:all_authors, 'Authors') %><br/>
    <%= form.autocomplete_field :all_authors, '/sources/autocomplete_authors_name', 'data-delimiter' => ', ', 'data-auto-focus' => true, :fields => {:all_authors => '#all_authors'}, class: ['autocomplete', 'form-control'], id: 'all_authors', value: @author %>
  </div>

  <div>
    <%= label_tag(:source_type, 'Type') %><br>
    <%= form.text_field :source_type, :size => '20', :maxlength => '20', class: 'form-control', id: 'source_type' %>
  </div>

  <div>
    <%= label_tag(:notes, 'Notes') %><br>
    <%= form.text_area :notes, size: '80x3', class: 'form-control', id: 'notes' %>
  </div>

  <div>
    <%= label_tag(:all_tags, 'Tags') %><br/>
    <%= form.autocomplete_field :all_tags, '/tags/autocomplete_tags_title', 'data-delimiter' => ', ', 'data-auto-focus' => true, :fields => {:all_tags => '#all_tags'}, class: ['autocomplete', 'form-control'], id: 'all_tags' %>
  </div>

  <div>
    <%= label_tag(:file, 'Image') %><br/>
    <%= image_tag(@source.file_url) if @source.file? %>
    <%= form.file_field :file, id: 'file' %>
    <%= form.hidden_field :file_cache %>
  </div>

  <div>
    <label>
      <%= form.check_box :remove_file %>
      Remove image
    </label>
  </div>

  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div>
    <%= form.submit 'Save Source', {class: ['btn', 'btn-primary']} %>
    <%= form.button 'Back', {class: ['btn']} %>
  </div>

<% end %>

docroot/app/views/sources/_sources.html.erb
<% if !sources.empty? %>
  <table class="sources">
    <caption>Sources</caption>
    <thead>
      <tr>
        <th class="title">Title</th>
        <th class="author">Author(s)</th>
        <th class="source_type">Type</th>
        <th class="tags">Tags</th>
        <th class="operations">Operations</th>
      </tr>
    </thead>

    <tbody>
      <% sources.each do |source| %>
        <%
          # Bold matching search text.
          unless @search.blank?
            source.title = raw source.title.gsub(/#{@search}/i, '<b>\0</b>')
          end
        %>
        <tr class="source-<%= source.id %>">
          <td class="title"><%= link_to source.title.html_safe, source_path(source) %></td>
          <td class="author"><%= print_authors(source) %></td>
          <td class="source_type"><%= source.source_type %></td>
          <td class="tags"><%= raw tag_links(source.all_tags) %></td>
          <td class="operations">
            <%= link_to fa_icon('pencil'), edit_source_path(source), id: 'edit-source-' + source.id.to_s, class: ['edit'] %>
            <%= link_to fa_icon('book'), 'bear://x-callback-url/search?term=' + source.title, class: ['bear-source', 'gray'] %>
            <%= link_to fa_icon('ban'), source_path(source),
                  method: :delete,
                  data: { confirm: 'Are you sure that you want to delete ' + source.title + '? This will also delete any highlights from this source.' },
                  id: 'delete-source-' + source.id.to_s,
                  class: ['delete', 'gray'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

docroot/app/views/sources/edit.html.erb
<%= content_for(:title, 'Edit Source: ' + @source.title) %>
<h1>Edit source</h1>
 
<%= render 'form' %>

docroot/app/views/sources/index.html.erb
<%= content_for(:title, 'Sources') %>
<h1>Sources</h1>

<%= link_to 'New source', new_source_path, class: ['badge', 'badge-pill', 'badge-primary'] %>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag :source_type %>
  <%= select_tag :source_type, options_from_collection_for_select(@source_types, 'source_type', 'source_type', params[:source_type]), include_blank: true %>
  <%= label_tag 'Sort' %>
  <%= select_tag 'sort', options_for_select([['Title', 'title'], ['Last Added', 'newest']], params[:sort] ? params[:sort] : 'newest') %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'sources', locals: { sources: @sources } %>

docroot/app/views/sources/new.html.erb
<%= content_for(:title, 'New Source') %>
<h1>New Source</h1>

<%= render 'form' %>

docroot/app/views/sources/show.html.erb
<%= content_for(:title, @source.title) %>
<h1><%= @source.title %></h1>

<div>
  <%= link_to 'Search Bear', 'bear://x-callback-url/search?term=' + @source.title, class: ['badge', 'badge-pill', 'badge-secondary'] %>
  <%= link_to 'Edit Source', edit_source_path(@source), class: ['badge', 'badge-pill', 'badge-light'] %>
  <%= link_to 'Add Highlight', new_highlight_path(:source => @source.id), class: ['badge', 'badge-pill', 'badge-primary'] %>
</div>

<div class="favorites-highlights">
  <strong>Favorites / Highlights:</strong>
  <%= @favorites_count %> / <%= @highlights_count %>
</div>

<div class="author">
  <strong>Author(s):</strong>
  <%= print_authors(@source) %>
</div>

<div class="tags">
  <strong>Tags:</strong>
  <%= raw tag_links(@source.tags) %>
</div>

<div class="type">
  <strong>Type:</strong>
  <%= @source.source_type %>
</div>

<% if @source.notes %>
  <div class="notes">
    <strong>Notes:</strong>
    <%= simple_format @markdown.render(@source.notes || '') %>
  </div>
<% end %>

<% unless @source.file.blank? %>
  <div class="image">
    <strong>Image:</strong>
    <p><%= image_tag(@source.file_url) %></p>
  </div>
<% end %>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag :tag %>
  <%= select_tag :tag, options_from_collection_for_select(@tags, 'title', 'title', params[:tag]), include_blank: true, class: 'chosen-select', multiple: true %>
  <%= label_tag :favorite %>
  <%= check_box_tag :favorite, '1', params[:favorite] %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'highlights/highlights', locals: { highlights: @highlights, hide: ['source', 'author'] } %>