docroot/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Deleted/unpublished routes.
  get "highlights/:id/publish", to: "highlights#publish"
  get "highlights/:id/unpublish", to: "highlights#unpublish"
  get "highlights/deleted", to: "highlights#deleted"
  get "highlights/untagged", to: "highlights#untagged"

  # Favorites routes.
  get "highlights/:id/favorite", to: "highlights#favorite"
  get "highlights/:id/unfavorite", to: "highlights#unfavorite"
  get "favorites", to: "highlights#favorites"

  # Search.
  get "highlights/search", to: "highlights#search"

  # Tags.
  get "tags/merge", to: "tags#merge"
  post "tags/merge", to: "tags#merge_post"

  # Autocomplete.
  resources :tags do
    get :autocomplete_tags_title, on: :collection
  end
  resources :sources do
    get :autocomplete_authors_name, on: :collection
  end

  # Resources.
  resources :authors
  resources :highlights
  resources :sources
  resources :tags

  # User settings.
  get "settings", to: "users#settings"
  patch "user/:id", to: "users#update", as: :user

  # Import.
  get "import", to: "import#form"
  post "import", to: "import#import"
  post "upload", to: "import#upload"

  # Root page.
  root "highlights#index"
end

docroot/app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  include Authors
  include ByUser
  include Tags

  belongs_to :user
  has_many :sources_authors, dependent: :delete_all
  has_many :sources, through: :sources_authors
  has_many :author_taggings, dependent: :delete_all
  has_many :tags, through: :author_taggings
  validates :user_id, numericality: { only_integer: true }
  validates_presence_of :name, message: "is required"
end

docroot/app/models/concerns/authors.rb
# frozen_string_literal: true

module Authors
  extend ActiveSupport::Concern

  # Find or create each of the tags from the comma separated list.
  def all_authors=(authors_and_user)
    # Break out the comma separated tag titles from the user ID.
    authors = authors_and_user[0]
    user_id = authors_and_user[1]

    if authors.present?
      # Reject any 'blank' entries between commas.
      authors = authors.split(",").reject(&:blank?)
      self.authors = authors.map do |author|
        Author.where(name: author.strip, user_id: user_id).first_or_create!
      end
    end
  end

  # Display all authors as comma separated.
  def all_authors
    self.authors.map(&:name).join(", ")
  end
end

docroot/app/controllers/authors_controller.rb
# frozen_string_literal: true

# Authors controller.
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  require "will_paginate/array"
  include AuthorsControllerConcern

  # Create a new author.
  def new
    @author = Author.new
  end

  # List authors by user.
  def index
    @authors = current_user.authors

    # Sort.
    if params[:sort] == "newest"
      @authors = @authors.sort_by(&:created_at).reverse
    else
      @authors = @authors.sort_by(&:name)
    end
  end

  # Show an author.
  def show
    @author = current_user.authors.find(params[:id])
    @sources = @author.sources
    @highlights_count = author_highlights_count(@author)
    @favorites_count = author_highlights_count(@author, true)
  end

  # Edit an existing author.
  def edit
    @author = current_user.authors.find(params[:id])
  end

  # Update an existing author.
  def update
    @author = current_user.authors.find(params[:id])

    # Change all_tags to be an array containing the comma separated list of tags
    # and the current user ID. We need the user ID in order to save the tag to
    # the correct user when creating a new highlight, since the highlight
    # doesn't already have the user_id saved.
    params = author_params.merge('all_tags': [
      author_params["all_tags"],
      author_params["user_id"]
    ])

    if @author.update(params)
      redirect_to @author
    else
      render "edit"
    end
  end

  # Create a new author.
  def create
    # Change all_tags to be an array containing the comma separated list of tags
    # and the current user ID. We need the user ID in order to save the tag to
    # the correct user when creating a new highlight, since the highlight
    # doesn't already have the user_id saved.
    params = author_params.merge('all_tags': [
      author_params["all_tags"],
      author_params["user_id"]
    ])

    @author = Author.new(params)

    if @author.save
      redirect_to @author
    else
      render "new"
    end
  end

  # Delete an author.
  def destroy
    @author = current_user.authors.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
    # Define which author fields are required and permitted.
    def author_params
      params.require(:author).permit(:name, :type, :all_tags, :user_id)
    end
end

docroot/app/controllers/concerns/authors.rb
# frozen_string_literal: true

module Authors
  extend ActiveSupport::Concern

  # Get highlights count for an author.
  def author_highlights_count(author, favorites = false)
    @count = 0
    @sources = author.sources
    @sources.each do |source|
      if favorites
        @count += source.highlights.where(published: true, favorite: true).count
      else
        @count += source.highlights.where(published: true).count
      end
    end
    @count
  end
end

docroot/app/helpers/authors_helper.rb
# frozen_string_literal: true

module AuthorsHelper
end

docroot/app/views/authors/_authors.html.erb
<% if !authors.empty? %>
  <table class="authors">
    <caption>Authors</caption>
    <thead>
      <tr>
        <th class="author">Author</th>
        <th class="tags">Tags</th>
        <th class="operations">Operations</th>
      </tr>
    </thead>

    <tbody>
      <% authors.each do |author| %>
        <%
          # Bold matching search text.
          unless @search.blank?
            author.name = author.name.gsub(/#{@search}/i, '<b>\0</b>')
          end
        %>
        <tr class="author-<%= author.id %>">
          <td class="author"><%= link_to author.name.html_safe, author_path(author.id) %></td>
          <td class="tags"><%= raw tag_links(author.all_tags) %></td>
          <td class="operations">
            <%= link_to fa_icon('pencil'), edit_author_path(author), id: 'edit-author-' + author.id.to_s, class: ['edit'] %>
            <%= link_to fa_icon('book'), 'bear://x-callback-url/search?term=' + author.name, class: ['bear-author', 'gray'] %>
            <%= link_to fa_icon('ban'), author_path(author),
                  method: :delete,
                  data: { confirm: 'Are you sure that you want to delete ' + author.name + '?' },
                  id: 'delete-author-' + author.id.to_s,
                  class: ['delete', 'gray'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

docroot/app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= label_tag(:name) %><br/>
    <%= form.text_field :name, class: 'form-control', id: 'name' %>
  </div>

  <div>
    <%= label_tag(:tags) %><br/>
    <%= form.autocomplete_field :all_tags, '/tags/autocomplete_tags_title', 'data-delimiter' => ', ', 'data-auto-focus' => true, :fields => {:all_tags => '#all_tags'}, class: ['autocomplete', 'form-control'], id: 'all_tags' %>
  </div>

  <div>
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div>
    <%= form.submit 'Save Author', {class: ['btn', 'btn-primary']} %>
    <%= form.button 'Back', {class: ['btn']} %>
  </div>

<% end %>

docroot/app/views/authors/edit.html.erb
<%= content_for(:title, 'Edit Author: ' + @author.name) %>
<h1>Edit author</h1>

<%= render 'form' %>

docroot/app/views/authors/index.html.erb
<%= content_for(:title, 'Authors') %>
<h1>Authors</h1>

<%= link_to 'New author', new_author_path, class: ['badge', 'badge-pill', 'badge-primary'] %>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag 'Sort' %>
  <%= select_tag 'sort', options_for_select([['Name', 'name'], ['Last Added', 'newest']], params[:sort]) %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'authors', locals: { authors: @authors } %>

docroot/app/views/authors/new.html.erb
<%= content_for(:title, 'New Author') %>
<h1>New Author</h1>

<%= render 'form' %>

docroot/app/views/authors/show.html.erb
<%= content_for(:title, @author.name) %>
<h1><%= @author.name %></h1>

<div>
  <%= link_to 'Search Bear', 'bear://x-callback-url/search?term=' + @author.name, class: ['badge', 'badge-pill', 'badge-secondary'] %>
  <%= link_to 'Edit Author', edit_author_path(@author), class: ['badge', 'badge-pill', 'badge-light'] %>
  <%= link_to 'Add Source', new_source_path(:author => @author.name), class: ['badge', 'badge-pill', 'badge-primary'] %>
</div>

<div class="favorites-highlights">
  <strong>Favorites / Highlights:</strong>
  <%= @favorites_count %> / <%= @highlights_count %>
</div>

<div class="tags">
  <strong>Tags:</strong>
  <%= raw tag_links(@author.tags) %>
</div>

<%= render partial: 'sources/sources', locals: { sources: @sources } %>