docroot/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  # Deleted/unpublished routes.
  get "highlights/:id/publish", to: "highlights#publish"
  get "highlights/:id/unpublish", to: "highlights#unpublish"
  get "highlights/deleted", to: "highlights#deleted"
  get "highlights/untagged", to: "highlights#untagged"

  # Favorites routes.
  get "highlights/:id/favorite", to: "highlights#favorite"
  get "highlights/:id/unfavorite", to: "highlights#unfavorite"
  get "favorites", to: "highlights#favorites"

  # Search.
  get "highlights/search", to: "highlights#search"

  # Tags.
  get "tags/merge", to: "tags#merge"
  post "tags/merge", to: "tags#merge_post"

  # Autocomplete.
  resources :tags do
    get :autocomplete_tags_title, on: :collection
  end
  resources :sources do
    get :autocomplete_authors_name, on: :collection
  end

  # Resources.
  resources :authors
  resources :highlights
  resources :sources
  resources :tags

  # User settings.
  get "settings", to: "users#settings"
  patch "user/:id", to: "users#update", as: :user

  # Import.
  get "import", to: "import#form"
  post "import", to: "import#import"
  post "upload", to: "import#upload"

  # Root page.
  root "highlights#index"
end

docroot/app/models/highlight.rb
# frozen_string_literal: true

class Highlight < ApplicationRecord
  include Authors
  include ByUser
  include Tags

  belongs_to :user
  belongs_to :source
  has_many :taggings, dependent: :delete_all
  has_many :tags, through: :taggings
  validates_numericality_of :user_id, equal_to: Proc.new { |highlight|
    highlight.source.user_id.nil? ? 0 : highlight.source.user_id
  }
  validates :user_id, numericality: { only_integer: true }
  validates :source_id, numericality: { only_integer: true }
  validates_with HighlightSourceValidator
  validates_with HighlightTagValidator
  validates_presence_of :highlight, message: "is required"

  # Find highlights tagged with the tag.
  def self.tagged_with(titles)
    if titles.kind_of?(Array)
      @highlights = []
      titles.each do |title|
        @highlights += Tag.find_by_title!(title).highlights
      end
    else
      @highlights = Tag.find_by_title!(titles).highlights.to_a
    end
    @highlights.uniq
  rescue ActiveRecord::RecordNotFound
    []
  end

  # Filter highlights by authors that have sources that have those highlights.
  def self.by_author(id)
    self.joins("JOIN sources ON highlights.source_id = sources.id JOIN sources_authors ON sources.id = sources_authors.source_id").where(highlights: { published: true }, sources_authors: { author_id: id }).distinct
  end

  # Get highlights that aren't tagged with any tag.
  def self.not_tagged
    self.joins("LEFT JOIN taggings ON taggings.highlight_id = highlights.id").where(highlights: { published: true }, taggings: { id: nil }).distinct
  end
end

docroot/app/controllers/highlights_controller.rb
# frozen_string_literal: true

# Highlights controller.
class HighlightsController < ApplicationController
  include TagsControllerConcern
  require "will_paginate/array"

  def search
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    if params["search"].present?
      search = params["search"]
      model = params["model"].blank? ? "All" : params["model"]
      @highlights = @sources = @authors = @tags = []

      if ["All", "Highlights"].include? model
        @highlights = current_user.highlights.where("highlight LIKE ? OR note LIKE ?", "%#{search}%", "%#{search}%").where(published: true)
      end

      if ["All", "Sources"].include? model
        @sources = current_user.sources.where("title LIKE ?", "%#{search}%")
      end

      if ["All", "Authors"].include? model
        @authors = current_user.authors.where("name LIKE ?", "%#{search}%")
      end

      if ["All", "Tags"].include? model
        @tags = tags_with_count
        @tags = @tags.where("title LIKE ?", "%#{search}%")
      end
    end
  end

  # Create new highlight.
  def new
    @highlight = Highlight.new
    @tags = Tag.all
    @source = nil
    session[:return_to] = request.referer
    if params[:source]
      @source = params[:source]
    end
  end

  # Show a list of highlights by the user.
  def index
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @authors = current_user.authors.order(:name)
    @highlights = current_user.highlights.where(published: true)

    if params[:favorite].present?
      @highlights = @highlights.where(favorite: true)
    end

    if params[:tag].present?
      @highlights = @highlights.tagged_with(params[:tag])
    end

    if params[:author].present?
      @highlights = @highlights.by_author(params[:author])
      @tags = current_user.tags.by_author(params[:author]).where(highlights: { published: true }).distinct.order(:title)
    else
      @tags = current_user.tags.joins(:highlights).where(highlights: { published: true }).distinct.order(:title)
    end

    @highlights = @highlights.sort_by(&:created_at).reverse
    @highlights = @highlights.paginate(page: params[:page], per_page: 20)
  end

  # Show favorite highlights by the user.
  def favorites
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @authors = current_user.authors.order(:name)
    @highlights = current_user.highlights.where(favorite: true, published: true)

    if params[:tag].present?
      @highlights = @highlights.tagged_with(params[:tag])
    end

    if params[:author].present?
      @highlights = @highlights.by_author(params[:author])
      @tags = current_user.tags.by_author(params[:author]).where(highlights: { favorite: true, published: true }).distinct.order(:title)
    else
      @tags = current_user.tags.joins(:highlights).where(highlights: { favorite: true, published: true }).distinct.order(:title)
    end

    @highlights = @highlights.paginate(page: params[:page], per_page: 20)
  end

  # Show a list of untagged highlights.
  def untagged
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @highlights = current_user.highlights.not_tagged.paginate(page: params[:page], per_page: 20)
  end

  # Show a list of deleted (unpublished) highlights.
  def deleted
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    @tags = current_user.tags.joins(:highlights).where(highlights: { published: false }).distinct.order(:title)
    @highlights = current_user.highlights.where(published: false)
    if params[:tag].present?
      @highlights = @highlights.tagged_with(params[:tag])
    end
    @highlights = @highlights.paginate(page: params[:page], per_page: 20)
  end

  # Edit an existing highlight.
  def edit
    @highlight = current_user.highlights.find(params[:id])
    @source = @highlight.source_id
    @tags = Tag.all
    session[:return_to] = request.referer
  end

  # Update an existing highlight.
  def update
    @highlight = current_user.highlights.find(params[:id])
    @source = @highlight.source_id
    @tags = Tag.all

    # Change all_tags to be an array containing the comma separated list of tags
    # and the current user ID. We need the user ID in order to save the tag to
    # the correct user when creating a new highlight, since the highlight
    # doesn't already have the user_id saved.
    params = highlight_params.merge('all_tags': [
      highlight_params["all_tags"],
      highlight_params["user_id"]
    ])

    if @highlight.update(params)
      redirect_to session[:return_to]
    else
      render "edit"
    end
  end

  # Create a new highlight.
  def create
    # Change all_tags to be an array containing the comma separated list of tags
    # and the current user ID. We need the user ID in order to save the tag to
    # the correct user when creating a new highlight, since the highlight
    # doesn't already have the user_id saved.
    params = highlight_params.merge('all_tags': [
      highlight_params["all_tags"],
      highlight_params["user_id"]
    ])

    @highlight = Highlight.new(params)

    if @highlight.save
      redirect_to session[:return_to]
    else
      render "new"
    end
  end

  # Favorite a highlight. Ajax callback.
  def favorite
    @highlight = current_user.highlights.find(params[:id])
    @highlight.favorite = true
    @highlight.save
    render json: @highlight
  end

  # Unfavorite a highlight. Ajax callback.
  def unfavorite
    @highlight = current_user.highlights.find(params[:id])
    @highlight.favorite = false
    @highlight.save
    render json: @highlight
  end

  # Publish a highlight with ajax call.
  def publish
    @highlight = current_user.highlights.find(params[:id])
    @highlight.published = true
    @highlight.save
    render json: @highlight
  end

  # Unpublish a highlight with ajax call.
  def unpublish
    @highlight = current_user.highlights.find(params[:id])
    @highlight.published = false
    @highlight.save
    render json: @highlight
  end

  # Unpublish a highlight (not actually delete).
  def destroy
    @highlight = current_user.highlights.find(params[:id])
    @highlight.published = false
    @highlight.save

    redirect_to highlights_path
  end

  private
    # Define which highlight fields are required and permitted.
    def highlight_params
      params.require(:highlight).permit(:highlight, :note, :location, :all_tags, :favorite, :published, :user_id, :source_id)
    end
end

docroot/app/helpers/highlights_helper.rb
# frozen_string_literal: true

module HighlightsHelper
end

docroot/app/views/highlights/_form.html.erb
<%= form_with model: @highlight, local: true do |form| %>

  <% if @highlight.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@highlight.errors.count, "error") %> prohibited
        this highlight from being saved:
      </h2>
      <ul>
        <% @highlight.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag(:highlight) %><br/>
    <%= form.text_area :highlight, size: "80x5", class: 'form-control', id: 'highlight' %>
  </div>

  <div class="form-group">
    <%= label_tag(:note) %><br/>
    <%= form.text_area :note, size: "80x3", class: 'form-control', id: 'note' %>
  </div>

  <div class="form-group">
    <%= label_tag(:location) %><br/>
    <%= form.text_field :location, :size => '10', :maxlength => '10', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag(:tags) %><br/>
    <%= form.autocomplete_field :all_tags, '/tags/autocomplete_tags_title', 'data-delimiter' => ', ', 'data-auto-focus' => true, :fields => {:all_tags => '#all_tags'}, class: ['autocomplete', 'form-control'], id: 'all_tags' %>
  </div>

  <div class="form-group">
    <%= label_tag(:source) %><br/>
    <%= form.collection_select :source_id, current_user.sources.order(:title), :id, :title, {selected: @source, include_blank: false}, {class: 'form-control', id: 'source'}  %>
  </div>

  <div class="form-group form-checkbox">
    <%= label_tag(:favorite) %>
    <%= form.check_box :favorite, class: 'form-control', id: 'favorite' %>
  </div>

  <div class="form-group form-checkbox">
    <%= label_tag(:published) %>
    <%= form.check_box :published, class: 'form-control', id: 'published' %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save Highlight', {class: ['btn', 'btn-primary']} %>
    <%= form.button 'Back', {class: ['btn']} %>
  </div>

<% end %>

docroot/app/views/highlights/_highlights.html.erb
<% if !highlights.empty? %>
  <% if !defined?(hide) || !hide.include?('source') %>
    <table class="highlights">
  <% else %>
    <table class="highlights no-source">
  <% end %>
    <caption>Highlights</caption>
    <thead>
      <tr>
        <% if !defined?(hide) || !hide.include?('source') %>
          <th class="source">Source</th>
        <% end %>
        <% if !defined?(hide) || !hide.include?('author') %>
          <th class="author">Author(s)</th>
        <% end %>
        <th class="highlight">Highlight</th>
        <th class="note">Note</th>
        <th class="location">Location</th>
        <th class="tags">Tags</th>
        <th class="operations">Operations</th>
      </tr>
    </thead>

    <tbody>
      <% highlights.each do |highlight| %>
        <%
          # Bold matching search text.
          unless @search.blank?
            highlight.highlight = highlight.highlight.gsub(/#{@search}/i, '<b>\0</b>')
            if highlight.note
              highlight.note = highlight.note.gsub(/#{@search}/i, '<b>\0</b>')
            end
          end
        %>
        <tr id="highlight-<%= highlight.id %>">
          <% if !defined?(hide) || !hide.include?('source') %>
            <td class="source"><%= link_to highlight.source.title, source_path(highlight.source) %></td>
          <% end %>
          <% if !defined?(hide) || !hide.include?('author') %>
            <td class="author"><%= print_authors(highlight.source) %></td>
          <% end %>
          <td class="highlight"><%= simple_format @markdown.render(highlight.highlight || '') %></td>
          <td class="note"><%= simple_format @markdown.render(highlight.note || '') %></td>
          <td class="location"><%= highlight.location %></td>
          <td class="tags"><%= raw tag_links(highlight.all_tags) %></td>
          <td class="operations">
            <% id = highlight.id.to_s %>
            <%= link_to fa_icon('pencil'), edit_highlight_path(highlight), id: 'edit-highlight-' + id, class: ['edit'] %>
            <% if highlight.favorite %>
              <%= link_to fa_icon('heart'), '/highlights/' + id + '/unfavorite', id: 'favorite-' + id, class: ['favorite', 'red'], remote: true %>
            <% else %>
              <%= link_to fa_icon('heart'), '/highlights/' + id + '/favorite', id: 'favorite-' + id, class: ['favorite', 'gray'], remote: true %>
            <% end %>
            <% if highlight.url %>
              <%= link_to fa_icon('tablet'), highlight.url, id: 'tablet-' + id, class: ['tablet', 'gray'] %>
            <% end %>
            <% if highlight.published %>
              <%= link_to fa_icon('ban'), '/highlights/' + id + '/unpublish', id: 'publish-' + id, class: ['publish', 'gray'], remote: true %>
            <% else %>
              <%= link_to fa_icon('ban'), '/highlights/' + id + '/publish', id: 'publish-' + id, class: ['publish', 'red'], remote: true %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

docroot/app/views/highlights/create.js.erb
var new_highlight = $("<%= escape_javascript(render(partial: @highlight))%>").hide();
$('#highlights').prepend(new_highlight);
$('#highlight_<%= @highlight.id %>').fadeIn('slow');
$('#new_highlight')[0].reset();

docroot/app/views/highlights/deleted.html.erb
<%= content_for(:title, 'Deleted Highlights') %>
<h1>Deleted Highlights</h1>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag :tag %>
  <%= select_tag :tag, options_from_collection_for_select(@tags, 'title', 'title', params[:tag]), include_blank: true, class: 'chosen-select', multiple: true %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'highlights', locals: { highlights: @highlights } %>
<%= will_paginate @highlights, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

docroot/app/views/highlights/edit.html.erb
<%= content_for(:title, 'Edit Highlight') %>
<h1>Edit highlight</h1>
 
<%= render 'form' %>

docroot/app/views/highlights/favorites.html.erb
<%= content_for(:title, 'Highlights') %>
<h1>Favorites</h1>

<%= link_to 'New highlight', new_highlight_path, class: ['badge', 'badge-pill', 'badge-primary'] %>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag :author %>
  <%= select_tag :author, options_from_collection_for_select(@authors, 'id', 'name', params[:author]), include_blank: true, class: 'chosen-select' %>
  <%= label_tag :tag %>
  <%= select_tag :tag, options_from_collection_for_select(@tags, 'title', 'title', params[:tag]), include_blank: true, class: 'chosen-select', multiple: true %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'highlights', locals: { highlights: @highlights } %>
<%= will_paginate @highlights, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

docroot/app/views/highlights/index.html.erb
<%= content_for(:title, 'Highlights') %>
<h1>Highlights</h1>

<%= link_to 'New highlight', new_highlight_path, class: ['badge', 'badge-pill', 'badge-primary'] %>
<%= link_to 'Untagged Highlights', highlights_untagged_path, class: ['badge', 'badge-pill', 'badge-secondary'] %>
<%= link_to 'Deleted Highlights', highlights_deleted_path, class: ['badge', 'badge-pill', 'badge-secondary'] %>

<%= form_tag({}, :method => 'get', :class => 'filter-form') do %>
  <%= label_tag :author %>
  <%= select_tag :author, options_from_collection_for_select(@authors, 'id', 'name', params[:author]), include_blank: true, class: 'chosen-select' %>
  <%= label_tag :tag %>
  <%= select_tag :tag, options_from_collection_for_select(@tags, 'title', 'title', params[:tag]), include_blank: true, class: 'chosen-select', multiple: true %>
  <%= label_tag :favorite %>
  <%= check_box_tag :favorite, '1', params[:favorite] %>
  <%= submit_tag "Filter", :name => nil %>
<% end %>

<%= render partial: 'highlights', locals: { highlights: @highlights } %>
<%= will_paginate @highlights, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

docroot/app/views/highlights/index.js.erb
$('.favorite a').on('ajax:success', favoriteHighlight);
$('.publish a').on('ajax:success', publishHighlight);

function favoriteHighlight(event, data) {
  $(‘body’).append(data.id);
}

function publishHighlight(event, data) {
  $(‘body’).append(data.id);
}

docroot/app/views/highlights/new.html.erb
<%= content_for(:title, 'New Highlight') %>
<h1>New Highlight</h1>

<%= render 'form' %>

docroot/app/views/highlights/search.html.erb
<%= content_for(:title, 'Search Results') %>
<h1>Search Results</h1>

<% if @highlights.nil? && @sources.nil? && @authors.nil? && @tags.nil? %>
  <div>Please enter a search term.</div>
<% else %>
  <% if @highlights.empty? && @sources.empty? && @authors.empty? && @tags.empty? %>
    <div>No results found.</div>
  <% end %>

  <div>Try searching <%= link_to 'Bear App', 'bear://x-callback-url/search?term=' + params['search'] %>.</div>

  <%= render partial: 'highlights', locals: { highlights: @highlights, '@search': params['search'] } %>
  <%= render partial: 'sources/sources', locals: { sources: @sources, '@search': params['search'] } %>
  <%= render partial: 'authors/authors', locals: { authors: @authors, '@search': params['search'] } %>
  <%= render partial: 'tags/tags', locals: { tags: @tags, '@search': params['search'] } %>

<% end %>

docroot/app/views/highlights/untagged.html.erb
<%= content_for(:title, 'Untagged Highlights') %>
<h1>Untagged Highlights</h1>

<%= render partial: 'highlights', locals: { highlights: @highlights } %>
<%= will_paginate @highlights, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>